### ISSUE TITLE
DNS port should be configurable.

### ISSUE THREAD

**Issue by vitaly** [benjie/mehserve#10]
port `15353` that is hard-coded right now is also used by [corectl](https://github.com/TheNewNormal/corectl)

> Note: I also opened an issue on corectl: https://github.com/TheNewNormal/corectl/issues/106

**Comment by benjie** [comment]
Good spot. Would you be interested in building a PR for this? It'd need to tell people under macOS to modify [meh.resolver](https://github.com/benjie/mehserve/blob/1ae263a75c1965a9cfdd6601243b5fcdd017ed7a/meh.resolver#L3) before installing:

https://github.com/benjie/mehserve/blob/1ae263a75c1965a9cfdd6601243b5fcdd017ed7a/src/cli.coffee#L18-L19

You could do it by just making a `DNS_PORT` envvar like the `PORT` const here:

https://github.com/benjie/mehserve/blob/1ae263a75c1965a9cfdd6601243b5fcdd017ed7a/src/index.coffee#L9

**Comment by vitaly** [comment]
Sure, why not ;). Here you go: https://github.com/benjie/mehserve/pull/11

**Comment by benjie** [comment]
Awesome thanks; released as 1.1.3 👍
