### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by ovikholt** [benjie/mehserve#23]
Cool repo! It's working nicely.

However when I try to connect to my Vue app running at localhost:8080, through your proxy, I get a document containing "Invalid Host header". And that's all I get! (Directly at localhost:8080 it works fine). Do you know if this error is something that comes from mehserve?

**Comment by ovikholt** [comment]
Turns out it was Vue's fault. Fixed it by creating in project root

```
// vue.config.js
module.exports = {
    // options...
    devServer: {
        disableHostCheck: true
    }
}
```

**Comment by benjie** [comment]
Thank you for sharing the solution 🙏

**Comment by oliverpool** [comment]
Another solution would bet o use `allowedHosts`:
```
// vue.config.js
module.exports = {
    // options...
    devServer: {
        allowedHosts: [".meh"],
    }
}

```

**Comment by stevage** [comment]
I just ran into this issue as well - the above fixed it. I wonder if there is a way of alerting users about this situation ahead of time? I know the server can't exactly tell if it's proxying a Vue app, but maybe a note in the README or something? It must affect a lot of people, as Vue is popular, and this setting is off by default.
