### ISSUE TITLE
Request: more transparent configuration

### ISSUE THREAD

**Issue by stevage** [benjie/mehserve#26]
From what I can see in the readme:

- there is no listed location for the configuration file that mehserve is presumably writing to
- there is no command that lists registered ports
- there is no command to remove or modify registered ports, only add new ones

So, there's no way, short of digging through the code, to say, change the port of a registered service.

Now, by digging through the code, I can now see that service "foo" is registered as port 8081 simply by creating a file `~/.mehserve/foo` with contents `8081`.

I'd suggest:

- documenting this directory structure in the README
- a `mehserve ls` command that lists the registered services (by scanning that directory) with their ports

**Comment by benjie** [comment]
Closed in #28; a PR to add `list` and `remove` commands would be welcome.
