### ISSUE TITLE
so.. any plans on starting servers automatically, like pow does?

### ISSUE THREAD

**Issue by vitaly** [benjie/mehserve#7]
I mean, when I go to `foo.dev` which is configured with pow it will autostart the application, and close it after a while if not used.

**Comment by benjie** [comment]
Thanks for your question, but I'm afraid to say the answer is no, that's beyond the scope of this project. We follow the Unix philosophy of simple composable tools that do one thing well. AFAIK pow only supports auto-starting ruby/rack applications; mehserve is intended to be entirely development-stack agnostic and just proxy web and websocket requests to the relevant places.

A tool you could use in combination with mehserve to achieve this could be something like `xinetd`?
